IF
  Range([GOODCUTOFF],7)
  Allegiance(Myself,NEUTRAL)
  !See([PC.0.0.DRUID])
  !See([PC.0.0.RANGER])
  !See([PC.0.0.FIGHTER_DRUID])
  !See([PC.0.0.CLERIC_RANGER])
THEN
  RESPONSE #100
    Enemy()
END

IF
  AttackedBy([ANYONE],DEFAULT)
  Allegiance(Myself,NEUTRAL)
  !See([PC.0.0.DRUID])
  !See([PC.0.0.RANGER])
  !See([PC.0.0.FIGHTER_DRUID])
  !See([PC.0.0.CLERIC_RANGER])
THEN
  RESPONSE #100
    Enemy()
END