#!/bin/sh
rm bg1cre/ajantd.cre 2>>bgt/bash.debug
rm bg1cre/amnis2.cre 2>>bgt/bash.debug
rm bg1cre/archdr.cre 2>>bgt/bash.debug
rm bg1cre/avery.cre 2>>bgt/bash.debug
#rm bg1cre/bandit2.cre - this is now used by bgt-weidu
rm bg1cre/bandit3.cre 2>>bgt/bash.debug
rm bg1cre/bart8.cre 2>>bgt/bash.debug
rm bg1cre/bart9.cre 2>>bgt/bash.debug
rm bg1cre/bearpo2.cre 2>>bgt/bash.debug
rm bg1cre/beggba_a.cre 2>>bgt/bash.debug
rm bg1cre/beggba_b.cre 2>>bgt/bash.debug
rm bg1cre/beggba_c.cre 2>>bgt/bash.debug
rm bg1cre/beggba_d.cre 2>>bgt/bash.debug
rm bg1cre/blah6666.cre 2>>bgt/bash.debug
rm bg1cre/boyba1_b.cre 2>>bgt/bash.debug
rm bg1cre/boyba3.cre 2>>bgt/bash.debug
rm bg1cre/chickdef.cre 2>>bgt/bash.debug
rm bg1cre/cookge.cre 2>>bgt/bash.debug
rm bg1cre/cowled.cre 2>>bgt/bash.debug
rm bg1cre/cult4.cre 2>>bgt/bash.debug
rm bg1cre/cultass.cre 2>>bgt/bash.debug
rm bg1cre/d2dop.cre 2>>bgt/bash.debug
rm bg1cre/d2dur.cre 2>>bgt/bash.debug
rm bg1cre/d2kie.cre 2>>bgt/bash.debug
rm bg1cre/deagan.cre 2>>bgt/bash.debug
rm bg1cre/dean.cre 2>>bgt/bash.debug
rm bg1cre/dialogmo.cre 2>>bgt/bash.debug
rm bg1cre/digger_a.cre 2>>bgt/bash.debug
rm bg1cre/digger_b.cre 2>>bgt/bash.debug
rm bg1cre/digger_c.cre 2>>bgt/bash.debug
rm bg1cre/digger_d.cre 2>>bgt/bash.debug
rm bg1cre/digger_e.cre 2>>bgt/bash.debug
rm bg1cre/doppl7.cre 2>>bgt/bash.debug
rm bg1cre/drizzatt.cre 2>>bgt/bash.debug
rm bg1cre/drizzdef.cre 2>>bgt/bash.debug
rm bg1cre/druid2.cre 2>>bgt/bash.debug
rm bg1cre/druidc.cre 2>>bgt/bash.debug
rm bg1cre/edie.cre 2>>bgt/bash.debug
rm bg1cre/eldotd.cre 2>>bgt/bash.debug
rm bg1cre/elmins.cre 2>>bgt/bash.debug
rm bg1cre/ennahe.cre 2>>bgt/bash.debug
rm bg1cre/entar.cre 2>>bgt/bash.debug
rm bg1cre/erik3.cre 2>>bgt/bash.debug
rm bg1cre/erlinh.cre 2>>bgt/bash.debug
rm bg1cre/farm2.cre 2>>bgt/bash.debug
rm bg1cre/farmbe.cre 2>>bgt/bash.debug
rm bg1cre/farmwe.cre 2>>bgt/bash.debug
rm bg1cre/feldan.cre 2>>bgt/bash.debug
rm bg1cre/fenwic.cre 2>>bgt/bash.debug
rm bg1cre/ffowb3.cre 2>>bgt/bash.debug
rm bg1cre/flam8.cre 2>>bgt/bash.debug
rm bg1cre/flamc7.cre 2>>bgt/bash.debug
rm bg1cre/flind_a.cre 2>>bgt/bash.debug
rm bg1cre/flind_b.cre 2>>bgt/bash.debug
rm bg1cre/flind_c.cre 2>>bgt/bash.debug
rm bg1cre/ftowb1.cre 2>>bgt/bash.debug
rm bg1cre/ftowb2.cre 2>>bgt/bash.debug
rm bg1cre/ftowb3.cre 2>>bgt/bash.debug
rm bg1cre/ftowb4.cre 2>>bgt/bash.debug
rm bg1cre/ftowbe.cre 2>>bgt/bash.debug
rm bg1cre/ftowbesn.cre 2>>bgt/bash.debug
rm bg1cre/ftowfr_a.cre 2>>bgt/bash.debug
rm bg1cre/ftowfr_c.cre 2>>bgt/bash.debug
rm bg1cre/ftowfrsn.cre 2>>bgt/bash.debug
rm bg1cre/ftowna_c.cre 2>>bgt/bash.debug
rm bg1cre/ftowna_d.cre 2>>bgt/bash.debug
rm bg1cre/ftownasc.cre 2>>bgt/bash.debug
rm bg1cre/ftowubsc.cre 2>>bgt/bash.debug
rm bg1cre/ftowubsn.cre 2>>bgt/bash.debug
rm bg1cre/ftwbax.cre 2>>bgt/bash.debug
rm bg1cre/furnel.cre 2>>bgt/bash.debug
rm bg1cre/galkin.cre 2>>bgt/bash.debug
rm bg1cre/gateke.cre 2>>bgt/bash.debug
rm bg1cre/gibber02.cre 2>>bgt/bash.debug
rm bg1cre/girba3_b.cre 2>>bgt/bash.debug
rm bg1cre/girba3_d.cre 2>>bgt/bash.debug
rm bg1cre/girba3_e.cre 2>>bgt/bash.debug
rm bg1cre/girlbax.cre 2>>bgt/bash.debug
rm bg1cre/girlbe.cre 2>>bgt/bash.debug
rm bg1cre/glowtes2.cre 2>>bgt/bash.debug
rm bg1cre/glowtest.cre 2>>bgt/bash.debug
#rm bg1cre/gnoll02.cre - used by sobh/dsotsc/ntotsc
#rm bg1cre/gnoll03.cre - used by sobh/dsotsc/ntotsc
rm bg1cre/gnoll04.cre 2>>bgt/bash.debug
rm bg1cre/gnoll05.cre 2>>bgt/bash.debug
rm bg1cre/gnoll2.cre 2>>bgt/bash.debug
#rm bg1cre/gnoll3.cre - used by sobh/dsotsc/ntotsc
rm bg1cre/govern.cre 2>>bgt/bash.debug
rm bg1cre/guarbe.cre 2>>bgt/bash.debug
rm bg1cre/guarca.cre 2>>bgt/bash.debug
rm bg1cre/haffg2.cre 2>>bgt/bash.debug
rm bg1cre/halfen.cre 2>>bgt/bash.debug
rm bg1cre/halfen2.cre 2>>bgt/bash.debug
rm bg1cre/halfg2.cre 2>>bgt/bash.debug
rm bg1cre/hasten.cre 2>>bgt/bash.debug
rm bg1cre/hentold.cre 2>>bgt/bash.debug
rm bg1cre/hobgo2.cre 2>>bgt/bash.debug
rm bg1cre/hobgo3.cre 2>>bgt/bash.debug
rm bg1cre/hobgo4.cre 2>>bgt/bash.debug
rm bg1cre/hobgo6.cre 2>>bgt/bash.debug
rm bg1cre/hobgob03.cre 2>>bgt/bash.debug
rm bg1cre/hobgob04.cre 2>>bgt/bash.debug
rm bg1cre/hobgob05.cre 2>>bgt/bash.debug
rm bg1cre/hobgod.cre 2>>bgt/bash.debug
rm bg1cre/ignati.cre 2>>bgt/bash.debug
rm bg1cre/ironho.cre 2>>bgt/bash.debug
rm bg1cre/jeb.cre 2>>bgt/bash.debug
rm bg1cre/jellyco.cre 2>>bgt/bash.debug
rm bg1cre/keelor.cre 2>>bgt/bash.debug
rm bg1cre/kiel.cre 2>>bgt/bash.debug
rm bg1cre/kobold02.cre 2>>bgt/bash.debug
rm bg1cre/kobold03.cre 2>>bgt/bash.debug
rm bg1cre/kobold10.cre 2>>bgt/bash.debug
rm bg1cre/kobold11.cre 2>>bgt/bash.debug
rm bg1cre/kobold12.cre 2>>bgt/bash.debug
rm bg1cre/kobold2.cre 2>>bgt/bash.debug
rm bg1cre/kobold4.cre 2>>bgt/bash.debug
rm bg1cre/kobold5.cre 2>>bgt/bash.debug
rm bg1cre/kobold6.cre 2>>bgt/bash.debug
rm bg1cre/kobold8.cre 2>>bgt/bash.debug
rm bg1cre/kobold9.cre 2>>bgt/bash.debug
rm bg1cre/krotan.cre 2>>bgt/bash.debug
rm bg1cre/lenore.cre 2>>bgt/bash.debug
rm bg1cre/llinde.cre 2>>bgt/bash.debug
rm bg1cre/lowlgu.cre 2>>bgt/bash.debug
rm bg1cre/malkal.cre 2>>bgt/bash.debug
rm bg1cre/mcook6.cre 2>>bgt/bash.debug
rm bg1cre/memnis.cre 2>>bgt/bash.debug
rm bg1cre/merch3.cre 2>>bgt/bash.debug
rm bg1cre/mercha.cre 2>>bgt/bash.debug
rm bg1cre/mergen.cre 2>>bgt/bash.debug
rm bg1cre/merlin.cre 2>>bgt/bash.debug
rm bg1cre/messed.cre 2>>bgt/bash.debug
rm bg1cre/monk.cre 2>>bgt/bash.debug
rm bg1cre/monkd2.cre 2>>bgt/bash.debug
rm bg1cre/monkde.cre 2>>bgt/bash.debug
rm bg1cre/monken.cre 2>>bgt/bash.debug
rm bg1cre/monktu15.cre 2>>bgt/bash.debug
rm bg1cre/monktu16.cre 2>>bgt/bash.debug
rm bg1cre/monktu17.cre 2>>bgt/bash.debug
rm bg1cre/monktu18.cre 2>>bgt/bash.debug
rm bg1cre/monktu19.cre 2>>bgt/bash.debug
rm bg1cre/monktu20.cre 2>>bgt/bash.debug
rm bg1cre/monktu6.cre 2>>bgt/bash.debug
rm bg1cre/mtbe12.cre 2>>bgt/bash.debug
rm bg1cre/mtob10.cre 2>>bgt/bash.debug
rm bg1cre/mtob4.cre 2>>bgt/bash.debug
rm bg1cre/mtob5.cre 2>>bgt/bash.debug
rm bg1cre/mtowfrsn.cre 2>>bgt/bash.debug
rm bg1cre/mtowna_e.cre 2>>bgt/bash.debug
rm bg1cre/mtownasn.cre 2>>bgt/bash.debug
rm bg1cre/mtowubsn.cre 2>>bgt/bash.debug
rm bg1cre/mtowubst.cre 2>>bgt/bash.debug
rm bg1cre/narrat2.cre 2>>bgt/bash.debug
rm bg1cre/nasha.cre 2>>bgt/bash.debug
rm bg1cre/nelori.cre 2>>bgt/bash.debug
rm bg1cre/nhuntc.cre 2>>bgt/bash.debug
rm bg1cre/nimfur.cre 2>>bgt/bash.debug
rm bg1cre/nobl13.cre 2>>bgt/bash.debug
rm bg1cre/nobl15.cre 2>>bgt/bash.debug
rm bg1cre/noblay.cre 2>>bgt/bash.debug
rm bg1cre/noblba.cre 2>>bgt/bash.debug
rm bg1cre/noblbaz.cre 2>>bgt/bash.debug
rm bg1cre/noblsn_a.cre 2>>bgt/bash.debug
rm bg1cre/noblsn_b.cre 2>>bgt/bash.debug
rm bg1cre/nobw6.cre 2>>bgt/bash.debug
rm bg1cre/nobwba_b.cre 2>>bgt/bash.debug
rm bg1cre/nobwba_c.cre 2>>bgt/bash.debug
rm bg1cre/nobwsn_a.cre 2>>bgt/bash.debug
rm bg1cre/nobwsn_b.cre 2>>bgt/bash.debug
rm bg1cre/ogre03.cre 2>>bgt/bash.debug
rm bg1cre/ogre04.cre 2>>bgt/bash.debug
rm bg1cre/ogre05.cre 2>>bgt/bash.debug
rm bg1cre/ogre_a.cre 2>>bgt/bash.debug
rm bg1cre/ogre_b.cre 2>>bgt/bash.debug
rm bg1cre/ogre_c.cre 2>>bgt/bash.debug
rm bg1cre/ogre_d.cre 2>>bgt/bash.debug
rm bg1cre/ogre_e.cre 2>>bgt/bash.debug
rm bg1cre/ogred.cre 2>>bgt/bash.debug
rm bg1cre/ogregr1.cre 2>>bgt/bash.debug
rm bg1cre/ogregr2.cre 2>>bgt/bash.debug
rm bg1cre/ogregr3.cre 2>>bgt/bash.debug
rm bg1cre/ogregr4.cre 2>>bgt/bash.debug
rm bg1cre/ogregr_a.cre 2>>bgt/bash.debug
rm bg1cre/ogreha1.cre 2>>bgt/bash.debug
rm bg1cre/ogreha2.cre 2>>bgt/bash.debug
rm bg1cre/ogreha3.cre 2>>bgt/bash.debug
rm bg1cre/ogreha4.cre 2>>bgt/bash.debug
rm bg1cre/ogreha5.cre 2>>bgt/bash.debug
rm bg1cre/ogreha_a.cre 2>>bgt/bash.debug
rm bg1cre/ogreha_c.cre 2>>bgt/bash.debug
rm bg1cre/ogreha_d.cre 2>>bgt/bash.debug
rm bg1cre/ogreha_e.cre 2>>bgt/bash.debug
rm bg1cre/ogremba.cre 2>>bgt/bash.debug
rm bg1cre/olivia.cre 2>>bgt/bash.debug
rm bg1cre/perfba.cre 2>>bgt/bash.debug
rm bg1cre/pique.cre 2>>bgt/bash.debug
rm bg1cre/pnask.cre 2>>bgt/bash.debug
rm bg1cre/priilm.cre 2>>bgt/bash.debug
rm bg1cre/prosba.cre 2>>bgt/bash.debug
rm bg1cre/prosba_a.cre 2>>bgt/bash.debug
rm bg1cre/prosbax.cre 2>>bgt/bash.debug
rm bg1cre/ray.cre 2>>bgt/bash.debug
rm bg1cre/read.cre 2>>bgt/bash.debug
rm bg1cre/read4.cre 2>>bgt/bash.debug
rm bg1cre/read5.cre 2>>bgt/bash.debug
rm bg1cre/read6.cre 2>>bgt/bash.debug
rm bg1cre/repman.cre 2>>bgt/bash.debug
rm bg1cre/retard.cre 2>>bgt/bash.debug
rm bg1cre/satos.cre 2>>bgt/bash.debug
rm bg1cre/servwg.cre 2>>bgt/bash.debug
rm bg1cre/serwen.cre 2>>bgt/bash.debug
rm bg1cre/sevsun.cre 2>>bgt/bash.debug
rm bg1cre/shadow2.cre 2>>bgt/bash.debug
rm bg1cre/shalas.cre 2>>bgt/bash.debug
rm bg1cre/shara.cre 2>>bgt/bash.debug
rm bg1cre/shartd.cre 2>>bgt/bash.debug
rm bg1cre/shelto.cre 2>>bgt/bash.debug
rm bg1cre/shiloc.cre 2>>bgt/bash.debug
rm bg1cre/shop02.cre 2>>bgt/bash.debug
rm bg1cre/shop05.cre 2>>bgt/bash.debug
rm bg1cre/shopkeg.cre 2>>bgt/bash.debug
rm bg1cre/shopkn2.cre 2>>bgt/bash.debug
rm bg1cre/silvgu.cre 2>>bgt/bash.debug
#rm bg1cre/skelet02.cre - used by sobh/dsotsc/ntotsc
rm bg1cre/skelmel.cre 2>>bgt/bash.debug
rm bg1cre/slave2.cre 2>>bgt/bash.debug
rm bg1cre/slave3.cre 2>>bgt/bash.debug
rm bg1cre/solia2.cre 2>>bgt/bash.debug
rm bg1cre/svlast.cre 2>>bgt/bash.debug
rm bg1cre/sword.cre 2>>bgt/bash.debug
rm bg1cre/tamoko2.cre 2>>bgt/bash.debug
rm bg1cre/tasloi02.cre 2>>bgt/bash.debug
rm bg1cre/tasloi03.cre 2>>bgt/bash.debug
rm bg1cre/tester.cre 2>>bgt/bash.debug
rm bg1cre/thug.cre 2>>bgt/bash.debug
rm bg1cre/tiaxd.cre 2>>bgt/bash.debug
rm bg1cre/travel.cre 2>>bgt/bash.debug
rm bg1cre/utor.cre 2>>bgt/bash.debug
rm bg1cre/valino.cre 2>>bgt/bash.debug
rm bg1cre/velvet.cre 2>>bgt/bash.debug
rm bg1cre/verlin.cre 2>>bgt/bash.debug
rm bg1cre/voice.cre 2>>bgt/bash.debug
rm bg1cre/volose.cre 2>>bgt/bash.debug
rm bg1cre/wareho.cre 2>>bgt/bash.debug
rm bg1cre/warehx.cre 2>>bgt/bash.debug
rm bg1cre/warrid.cre 2>>bgt/bash.debug
rm bg1cre/welt.cre 2>>bgt/bash.debug
rm bg1cre/werewogr.cre 2>>bgt/bash.debug
rm bg1cre/whitkd.cre 2>>bgt/bash.debug
rm bg1cre/wilton.cre 2>>bgt/bash.debug
rm bg1cre/wolfw2.cre 2>>bgt/bash.debug
rm bg1cre/wolfw3.cre 2>>bgt/bash.debug
rm bg1cre/womand.cre 2>>bgt/bash.debug
rm bg1cre/xvart02.cre 2>>bgt/bash.debug
rm bg1cre/xvart03.cre 2>>bgt/bash.debug
rm bg1cre/yeslid.cre 2>>bgt/bash.debug
#existing creatures 2>>bgt/bash.debug
rm bg1cre/bearbl.cre 2>>bgt/bash.debug
rm bg1cre/bearblsu.cre 2>>bgt/bash.debug
rm bg1cre/bearbr.cre 2>>bgt/bash.debug
rm bg1cre/bearbrsu.cre 2>>bgt/bash.debug
rm bg1cre/bearcasu.cre 2>>bgt/bash.debug
rm bg1cre/belt.cre 2>>bgt/bash.debug
rm bg1cre/bird.cre 2>>bgt/bash.debug
rm bg1cre/bjorni.cre 2>>bgt/bash.debug
rm bg1cre/boyba1.cre 2>>bgt/bash.debug
rm bg1cre/brage2.cre 2>>bgt/bash.debug
rm bg1cre/cat.cre 2>>bgt/bash.debug
rm bg1cre/catdead.cre 2>>bgt/bash.debug
rm bg1cre/catp.cre 2>>bgt/bash.debug
rm bg1cre/cow.cre 2>>bgt/bash.debug
rm bg1cre/cowh.cre 2>>bgt/bash.debug
rm bg1cre/davaeo.cre 2>>bgt/bash.debug
rm bg1cre/dogwasu.cre 2>>bgt/bash.debug
rm bg1cre/dogwisu.cre 2>>bgt/bash.debug
rm bg1cre/dreppi.cre 2>>bgt/bash.debug
rm bg1cre/dreppi2.cre 2>>bgt/bash.debug
rm bg1cre/dreppi3.cre 2>>bgt/bash.debug
rm bg1cre/fireb1.cre 2>>bgt/bash.debug
rm bg1cre/firebe.cre 2>>bgt/bash.debug
rm bg1cre/flam13.cre 2>>bgt/bash.debug
rm bg1cre/ghoulsu.cre 2>>bgt/bash.debug
rm bg1cre/gibbersu.cre 2>>bgt/bash.debug
rm bg1cre/gnollsu.cre 2>>bgt/bash.debug
rm bg1cre/gorion.cre 2>>bgt/bash.debug
rm bg1cre/gorion3.cre 2>>bgt/bash.debug
rm bg1cre/hobgobsu.cre 2>>bgt/bash.debug
rm bg1cre/horse.cre 2>>bgt/bash.debug
rm bg1cre/innke2.cre 2>>bgt/bash.debug
rm bg1cre/jellgr.cre 2>>bgt/bash.debug
rm bg1cre/jellmu.cre 2>>bgt/bash.debug
rm bg1cre/jelloc.cre 2>>bgt/bash.debug
rm bg1cre/jellygr.cre 2>>bgt/bash.debug
rm bg1cre/jondal.cre 2>>bgt/bash.debug
rm bg1cre/jondalw.cre 2>>bgt/bash.debug
rm bg1cre/keeper.cre 2>>bgt/bash.debug
rm bg1cre/koboldsu.cre 2>>bgt/bash.debug
rm bg1cre/liia.cre 2>>bgt/bash.debug
rm bg1cre/monktu1.cre 2>>bgt/bash.debug
rm bg1cre/nalin.cre 2>>bgt/bash.debug
rm bg1cre/nobw4.cre 2>>bgt/bash.debug
rm bg1cre/ogregrsu.cre 2>>bgt/bash.debug
rm bg1cre/phlydi.cre 2>>bgt/bash.debug
rm bg1cre/plyogre.cre 2>>bgt/bash.debug
rm bg1cre/plyspid.cre 2>>bgt/bash.debug
rm bg1cre/plywolf.cre 2>>bgt/bash.debug
rm bg1cre/poghm10.cre 2>>bgt/bash.debug
rm bg1cre/poghm9.cre 2>>bgt/bash.debug
rm bg1cre/poghma4.cre 2>>bgt/bash.debug
rm bg1cre/poghma5.cre 2>>bgt/bash.debug
rm bg1cre/poghma7.cre 2>>bgt/bash.debug
rm bg1cre/ragefa.cre 2>>bgt/bash.debug
rm bg1cre/rat.cre 2>>bgt/bash.debug
rm bg1cre/rat2.cre 2>>bgt/bash.debug
rm bg1cre/reevor.cre 2>>bgt/bash.debug
rm bg1cre/reevor2.cre 2>>bgt/bash.debug
rm bg1cre/reevor3.cre 2>>bgt/bash.debug
rm bg1cre/schlum.cre 2>>bgt/bash.debug
rm bg1cre/seagul.cre 2>>bgt/bash.debug
rm bg1cre/skelded.cre 2>>bgt/bash.debug
rm bg1cre/skele2.cre 2>>bgt/bash.debug
rm bg1cre/sleepdw.cre 2>>bgt/bash.debug
rm bg1cre/sleepfh.cre 2>>bgt/bash.debug
rm bg1cre/sleepmh.cre 2>>bgt/bash.debug
rm bg1cre/squirr.cre 2>>bgt/bash.debug
rm bg1cre/tasloisu.cre 2>>bgt/bash.debug
rm bg1cre/tethto2.cre 2>>bgt/bash.debug
rm bg1cre/tethto3.cre 2>>bgt/bash.debug
rm bg1cre/voieas.cre 2>>bgt/bash.debug
rm bg1cre/voinor.cre 2>>bgt/bash.debug
rm bg1cre/voisou.cre 2>>bgt/bash.debug
rm bg1cre/voiwes.cre 2>>bgt/bash.debug
rm bg1cre/voltin.cre 2>>bgt/bash.debug
rm bg1cre/watch2.cre 2>>bgt/bash.debug
rm bg1cre/watch3.cre 2>>bgt/bash.debug
rm bg1cre/watch6.cre 2>>bgt/bash.debug
rm bg1cre/watch9.cre 2>>bgt/bash.debug
rm bg1cre/winthr2.cre 2>>bgt/bash.debug
rm bg1cre/winthr3.cre 2>>bgt/bash.debug
rm bg1cre/wolfchar.cre 2>>bgt/bash.debug
rm bg1cre/wolfdi.cre 2>>bgt/bash.debug
rm bg1cre/wolfdisu.cre 2>>bgt/bash.debug
rm bg1cre/wolfsu.cre 2>>bgt/bash.debug
rm bg1cre/worgsu.cre 2>>bgt/bash.debug
rm bg1cre/xvartsu.cre 2>>bgt/bash.debug
#existing and unused creatures
rm bg1cre/bird_in.cre 2>>bgt/bash.debug
rm bg1cre/bird_ine.cre 2>>bgt/bash.debug
rm bg1cre/bird_inn.cre 2>>bgt/bash.debug
rm bg1cre/bird_ins.cre 2>>bgt/bash.debug
rm bg1cre/bird_inw.cre 2>>bgt/bash.debug
rm bg1cre/charbase.cre 2>>bgt/bash.debug
rm bg1cre/drunk2.cre 2>>bgt/bash.debug
rm bg1cre/e31.cre 2>>bgt/bash.debug
rm bg1cre/e32.cre 2>>bgt/bash.debug
rm bg1cre/e33.cre 2>>bgt/bash.debug
rm bg1cre/e34.cre 2>>bgt/bash.debug
rm bg1cre/e35.cre 2>>bgt/bash.debug
rm bg1cre/e36.cre 2>>bgt/bash.debug
rm bg1cre/poghm3.cre 2>>bgt/bash.debug
rm bg1cre/poghm6.cre 2>>bgt/bash.debug
rm bg1cre/poghm8.cre 2>>bgt/bash.debug
rm bg1cre/poghma.cre 2>>bgt/bash.debug
rm bg1cre/poghma3.cre 2>>bgt/bash.debug
rm bg1cre/poghma6.cre 2>>bgt/bash.debug
rm bg1cre/poghma8.cre 2>>bgt/bash.debug
rm bg1cre/squirl.cre 2>>bgt/bash.debug
#bgt-included npcs
rm bg1cre/ajanti4.cre 2>>bgt/bash.debug
rm bg1cre/ajanti6.cre 2>>bgt/bash.debug
rm bg1cre/ajanti.cre 2>>bgt/bash.debug
rm bg1cre/alora6.cre 2>>bgt/bash.debug
rm bg1cre/alora.cre 2>>bgt/bash.debug
rm bg1cre/branwe5.cre 2>>bgt/bash.debug
rm bg1cre/branwe.cre 2>>bgt/bash.debug
rm bg1cre/coran5.cre 2>>bgt/bash.debug
rm bg1cre/coran.cre 2>>bgt/bash.debug
rm bg1cre/dynahe2.cre 2>>bgt/bash.debug
rm bg1cre/dynahe4.cre 2>>bgt/bash.debug
rm bg1cre/dynahe6.cre 2>>bgt/bash.debug
rm bg1cre/dynahe.cre 2>>bgt/bash.debug
rm bg1cre/edwin2.cre 2>>bgt/bash.debug
rm bg1cre/edwin4.cre 2>>bgt/bash.debug
rm bg1cre/edwin6.cre 2>>bgt/bash.debug
rm bg1cre/edwin.cre 2>>bgt/bash.debug
rm bg1cre/eldoth5.cre 2>>bgt/bash.debug
rm bg1cre/eldoth.cre 2>>bgt/bash.debug
rm bg1cre/faldor5.cre 2>>bgt/bash.debug
rm bg1cre/faldor.cre 2>>bgt/bash.debug
rm bg1cre/garric2.cre 2>>bgt/bash.debug
rm bg1cre/garric4.cre 2>>bgt/bash.debug
rm bg1cre/garric6.cre 2>>bgt/bash.debug
rm bg1cre/garric.cre 2>>bgt/bash.debug
rm bg1cre/imoen1.cre 2>>bgt/bash.debug
rm bg1cre/imoen2.cre 2>>bgt/bash.debug
rm bg1cre/imoen4.cre 2>>bgt/bash.debug
rm bg1cre/imoen6.cre 2>>bgt/bash.debug
rm bg1cre/imoen.cre 2>>bgt/bash.debug
rm bg1cre/jaheir2.cre 2>>bgt/bash.debug
rm bg1cre/jaheir4.cre 2>>bgt/bash.debug
rm bg1cre/jaheir6.cre 2>>bgt/bash.debug
rm bg1cre/jaheir.cre 2>>bgt/bash.debug
rm bg1cre/kagain2.cre 2>>bgt/bash.debug
rm bg1cre/kagain4.cre 2>>bgt/bash.debug
rm bg1cre/kagain6.cre 2>>bgt/bash.debug
rm bg1cre/kagain.cre 2>>bgt/bash.debug
rm bg1cre/khalid2.cre 2>>bgt/bash.debug
rm bg1cre/khalid4.cre 2>>bgt/bash.debug
rm bg1cre/khalid6.cre 2>>bgt/bash.debug
rm bg1cre/khalid.cre 2>>bgt/bash.debug
rm bg1cre/kivan4.cre 2>>bgt/bash.debug
rm bg1cre/kivan6.cre 2>>bgt/bash.debug
rm bg1cre/kivan.cre 2>>bgt/bash.debug
rm bg1cre/minsc2.cre 2>>bgt/bash.debug
rm bg1cre/minsc4.cre 2>>bgt/bash.debug
rm bg1cre/minsc6.cre 2>>bgt/bash.debug
rm bg1cre/minsc.cre 2>>bgt/bash.debug
rm bg1cre/montar2.cre 2>>bgt/bash.debug
rm bg1cre/montar4.cre 2>>bgt/bash.debug
rm bg1cre/montar6.cre 2>>bgt/bash.debug
rm bg1cre/montar.cre 2>>bgt/bash.debug
rm bg1cre/quayle4.cre 2>>bgt/bash.debug
rm bg1cre/quayle6.cre 2>>bgt/bash.debug
rm bg1cre/quayle.cre 2>>bgt/bash.debug
rm bg1cre/safana4.cre 2>>bgt/bash.debug
rm bg1cre/safana6.cre 2>>bgt/bash.debug
rm bg1cre/safana.cre 2>>bgt/bash.debug
rm bg1cre/sharte4.cre 2>>bgt/bash.debug
rm bg1cre/sharte6.cre 2>>bgt/bash.debug
rm bg1cre/sharte.cre 2>>bgt/bash.debug
rm bg1cre/skie6.cre 2>>bgt/bash.debug
rm bg1cre/skie.cre 2>>bgt/bash.debug
rm bg1cre/tiax4.cre 2>>bgt/bash.debug
rm bg1cre/tiax6.cre 2>>bgt/bash.debug
rm bg1cre/tiax.cre 2>>bgt/bash.debug
rm bg1cre/viconi4.cre 2>>bgt/bash.debug
rm bg1cre/viconi6.cre 2>>bgt/bash.debug
rm bg1cre/viconi.cre 2>>bgt/bash.debug
rm bg1cre/xan4.cre 2>>bgt/bash.debug
rm bg1cre/xan6.cre 2>>bgt/bash.debug
rm bg1cre/xan.cre 2>>bgt/bash.debug
rm bg1cre/xzar2.cre 2>>bgt/bash.debug
rm bg1cre/xzar4.cre 2>>bgt/bash.debug
rm bg1cre/xzar6.cre 2>>bgt/bash.debug
rm bg1cre/xzar.cre 2>>bgt/bash.debug
rm bg1cre/yeslic5.cre 2>>bgt/bash.debug
rm bg1cre/yeslic.cre 2>>bgt/bash.debug