IF
  Global("GorpalEnemies","AR7216",1)
THEN
  RESPONSE #100
    SetGlobal("GorpalEnemies","AR7216",2)
    CreateCreature("GRETEK",[743.1041],0)  // ~Gretek~
    CreateCreature("PARGUS",[681.1029],0)  // ~Pargus~
    CreateCreature("WILF",[775.1135],0)  // ~Wilf~
    CreateCreature("NADER",[845.992],0)  // ~Nader~
    CreateCreature("ARLIN",[812.1057],0)  // ~Arlin~
    CreateCreature("CATURA",[376.1045],0)  // ~Caturak~
END

