@echo off

::delete unused cres
del bg1cre\ajantd.cre
del bg1cre\amnis2.cre
del bg1cre\archdr.cre
del bg1cre\avery.cre
::del bg1cre\bandit2.cre - this is now used by bgt-weidu
del bg1cre\bandit3.cre
del bg1cre\bart8.cre
del bg1cre\bart9.cre
del bg1cre\bearpo2.cre
del bg1cre\beggba_a.cre
del bg1cre\beggba_b.cre
del bg1cre\beggba_c.cre
del bg1cre\beggba_d.cre
del bg1cre\blah6666.cre
del bg1cre\boyba1_b.cre
del bg1cre\boyba3.cre
del bg1cre\chickdef.cre
del bg1cre\cookge.cre
del bg1cre\cowled.cre
del bg1cre\cult4.cre
del bg1cre\cultass.cre
del bg1cre\d2dop.cre
del bg1cre\d2dur.cre
del bg1cre\d2kie.cre
del bg1cre\deagan.cre
del bg1cre\dean.cre
del bg1cre\dialogmo.cre
del bg1cre\digger_a.cre
del bg1cre\digger_b.cre
del bg1cre\digger_c.cre
del bg1cre\digger_d.cre
del bg1cre\digger_e.cre
del bg1cre\doppl7.cre
del bg1cre\drizzatt.cre
del bg1cre\drizzdef.cre
del bg1cre\druid2.cre
del bg1cre\druidc.cre
del bg1cre\edie.cre
del bg1cre\eldotd.cre
del bg1cre\elmins.cre
del bg1cre\ennahe.cre
del bg1cre\entar.cre
del bg1cre\erik3.cre
del bg1cre\erlinh.cre
del bg1cre\farm2.cre
del bg1cre\farmbe.cre
del bg1cre\farmwe.cre
del bg1cre\feldan.cre
del bg1cre\fenwic.cre
del bg1cre\ffowb3.cre
del bg1cre\flam8.cre
del bg1cre\flamc7.cre
del bg1cre\flind_a.cre
del bg1cre\flind_b.cre
del bg1cre\flind_c.cre
del bg1cre\ftowb1.cre
del bg1cre\ftowb2.cre
del bg1cre\ftowb3.cre
del bg1cre\ftowb4.cre
del bg1cre\ftowbe.cre
del bg1cre\ftowbesn.cre
del bg1cre\ftowfr_a.cre
del bg1cre\ftowfr_c.cre
del bg1cre\ftowfrsn.cre
del bg1cre\ftowna_c.cre
del bg1cre\ftowna_d.cre
del bg1cre\ftownasc.cre
del bg1cre\ftowubsc.cre
del bg1cre\ftowubsn.cre
del bg1cre\ftwbax.cre
del bg1cre\furnel.cre
del bg1cre\galkin.cre
del bg1cre\gateke.cre
del bg1cre\gibber02.cre
del bg1cre\girba3_b.cre
del bg1cre\girba3_d.cre
del bg1cre\girba3_e.cre
del bg1cre\girlbax.cre
del bg1cre\girlbe.cre
del bg1cre\glowtes2.cre
del bg1cre\glowtest.cre
::del bg1cre\gnoll02.cre - used by sobh\dsotsc\ntotsc
::del bg1cre\gnoll03.cre - used by sobh\dsotsc\ntotsc
del bg1cre\gnoll04.cre
del bg1cre\gnoll05.cre
del bg1cre\gnoll2.cre
::del bg1cre\gnoll3.cre - used by sobh\dsotsc\ntotsc
del bg1cre\govern.cre
del bg1cre\guarbe.cre
del bg1cre\guarca.cre
del bg1cre\haffg2.cre
del bg1cre\halfen.cre
del bg1cre\halfen2.cre
del bg1cre\halfg2.cre
del bg1cre\hasten.cre
del bg1cre\hentold.cre
del bg1cre\hobgo2.cre
del bg1cre\hobgo3.cre
del bg1cre\hobgo4.cre
del bg1cre\hobgo6.cre
del bg1cre\hobgob03.cre
del bg1cre\hobgob04.cre
del bg1cre\hobgob05.cre
del bg1cre\hobgod.cre
del bg1cre\ignati.cre
del bg1cre\ironho.cre
del bg1cre\jeb.cre
del bg1cre\jellyco.cre
del bg1cre\keelor.cre
del bg1cre\kiel.cre
del bg1cre\kobold02.cre
del bg1cre\kobold03.cre
del bg1cre\kobold10.cre
del bg1cre\kobold11.cre
del bg1cre\kobold12.cre
del bg1cre\kobold2.cre
del bg1cre\kobold4.cre
del bg1cre\kobold5.cre
del bg1cre\kobold6.cre
del bg1cre\kobold8.cre
del bg1cre\kobold9.cre
del bg1cre\krotan.cre
del bg1cre\lenore.cre
del bg1cre\llinde.cre
del bg1cre\lowlgu.cre
del bg1cre\malkal.cre
del bg1cre\mcook6.cre
del bg1cre\memnis.cre
del bg1cre\merch3.cre
del bg1cre\mercha.cre
del bg1cre\mergen.cre
del bg1cre\merlin.cre
del bg1cre\messed.cre
del bg1cre\monk.cre
del bg1cre\monkd2.cre
del bg1cre\monkde.cre
del bg1cre\monken.cre
del bg1cre\monktu15.cre
del bg1cre\monktu16.cre
del bg1cre\monktu17.cre
del bg1cre\monktu18.cre
del bg1cre\monktu19.cre
del bg1cre\monktu20.cre
del bg1cre\monktu6.cre
del bg1cre\mtbe12.cre
del bg1cre\mtob10.cre
del bg1cre\mtob4.cre
del bg1cre\mtob5.cre
del bg1cre\mtowfrsn.cre
del bg1cre\mtowna_e.cre
del bg1cre\mtownasn.cre
del bg1cre\mtowubsn.cre
del bg1cre\mtowubst.cre
del bg1cre\narrat2.cre
del bg1cre\nasha.cre
del bg1cre\nelori.cre
del bg1cre\nhuntc.cre
del bg1cre\nimfur.cre
del bg1cre\nobl13.cre
del bg1cre\nobl15.cre
del bg1cre\noblay.cre
del bg1cre\noblba.cre
del bg1cre\noblbaz.cre
del bg1cre\noblsn_a.cre
del bg1cre\noblsn_b.cre
del bg1cre\nobw6.cre
del bg1cre\nobwba_b.cre
del bg1cre\nobwba_c.cre
del bg1cre\nobwsn_a.cre
del bg1cre\nobwsn_b.cre
del bg1cre\ogre03.cre
del bg1cre\ogre04.cre
del bg1cre\ogre05.cre
del bg1cre\ogre_a.cre
del bg1cre\ogre_b.cre
del bg1cre\ogre_c.cre
del bg1cre\ogre_d.cre
del bg1cre\ogre_e.cre
del bg1cre\ogred.cre
del bg1cre\ogregr1.cre
del bg1cre\ogregr2.cre
del bg1cre\ogregr3.cre
del bg1cre\ogregr4.cre
del bg1cre\ogregr_a.cre
del bg1cre\ogreha1.cre
del bg1cre\ogreha2.cre
del bg1cre\ogreha3.cre
del bg1cre\ogreha4.cre
del bg1cre\ogreha5.cre
del bg1cre\ogreha_a.cre
del bg1cre\ogreha_c.cre
del bg1cre\ogreha_d.cre
del bg1cre\ogreha_e.cre
del bg1cre\ogremba.cre
del bg1cre\olivia.cre
del bg1cre\perfba.cre
del bg1cre\pique.cre
del bg1cre\pnask.cre
del bg1cre\priilm.cre
del bg1cre\prosba.cre
del bg1cre\prosba_a.cre
del bg1cre\prosbax.cre
del bg1cre\ray.cre
del bg1cre\read.cre
del bg1cre\read4.cre
del bg1cre\read5.cre
del bg1cre\read6.cre
del bg1cre\repman.cre
del bg1cre\retard.cre
del bg1cre\satos.cre
del bg1cre\servwg.cre
del bg1cre\serwen.cre
del bg1cre\sevsun.cre
del bg1cre\shadow2.cre
del bg1cre\shalas.cre
del bg1cre\shara.cre
del bg1cre\shartd.cre
del bg1cre\shelto.cre
del bg1cre\shiloc.cre
del bg1cre\shop02.cre
del bg1cre\shop05.cre
del bg1cre\shopkeg.cre
del bg1cre\shopkn2.cre
del bg1cre\silvgu.cre
::del bg1cre\skelet02.cre - used by sobh\dsotsc\ntotsc
del bg1cre\skelmel.cre
del bg1cre\slave2.cre
del bg1cre\slave3.cre
del bg1cre\solia2.cre
del bg1cre\svlast.cre
del bg1cre\sword.cre
del bg1cre\tamoko2.cre
del bg1cre\tasloi02.cre
del bg1cre\tasloi03.cre
del bg1cre\tester.cre
del bg1cre\thug.cre
del bg1cre\tiaxd.cre
del bg1cre\travel.cre
del bg1cre\utor.cre
del bg1cre\valino.cre
del bg1cre\velvet.cre
del bg1cre\verlin.cre
del bg1cre\voice.cre
del bg1cre\volose.cre
del bg1cre\wareho.cre
del bg1cre\warehx.cre
del bg1cre\warrid.cre
del bg1cre\welt.cre
del bg1cre\werewogr.cre
del bg1cre\whitkd.cre
del bg1cre\wilton.cre
del bg1cre\wolfw2.cre
del bg1cre\wolfw3.cre
del bg1cre\womand.cre
del bg1cre\xvart02.cre
del bg1cre\xvart03.cre
del bg1cre\yeslid.cre

::existing creatures
del bg1cre\bearbl.cre
del bg1cre\bearblsu.cre
del bg1cre\bearbr.cre
del bg1cre\bearbrsu.cre
del bg1cre\bearcasu.cre
del bg1cre\belt.cre
del bg1cre\bird.cre
del bg1cre\bjorni.cre
del bg1cre\boyba1.cre
del bg1cre\brage2.cre
del bg1cre\cat.cre
del bg1cre\catdead.cre
del bg1cre\catp.cre
del bg1cre\cow.cre
del bg1cre\cowh.cre
del bg1cre\davaeo.cre
del bg1cre\dogwasu.cre
del bg1cre\dogwisu.cre
del bg1cre\dreppi.cre
del bg1cre\dreppi2.cre
del bg1cre\dreppi3.cre
del bg1cre\fireb1.cre
del bg1cre\firebe.cre
del bg1cre\flam13.cre
del bg1cre\ghoulsu.cre
del bg1cre\gibbersu.cre
del bg1cre\gnollsu.cre
del bg1cre\gorion.cre
del bg1cre\gorion3.cre
del bg1cre\hobgobsu.cre
del bg1cre\horse.cre
del bg1cre\innke2.cre
del bg1cre\jellgr.cre
del bg1cre\jellmu.cre
del bg1cre\jelloc.cre
del bg1cre\jellygr.cre
del bg1cre\jondal.cre
del bg1cre\jondalw.cre
del bg1cre\keeper.cre
del bg1cre\koboldsu.cre
del bg1cre\liia.cre
del bg1cre\monktu1.cre
del bg1cre\nalin.cre
del bg1cre\nobw4.cre
del bg1cre\ogregrsu.cre
del bg1cre\phlydi.cre
del bg1cre\plyogre.cre
del bg1cre\plyspid.cre
del bg1cre\plywolf.cre
del bg1cre\poghm10.cre
del bg1cre\poghm9.cre
del bg1cre\poghma4.cre
del bg1cre\poghma5.cre
del bg1cre\poghma7.cre
del bg1cre\ragefa.cre
del bg1cre\rat.cre
del bg1cre\rat2.cre
del bg1cre\reevor.cre
del bg1cre\reevor2.cre
del bg1cre\reevor3.cre
del bg1cre\schlum.cre
del bg1cre\seagul.cre
del bg1cre\skelded.cre
del bg1cre\skele2.cre
del bg1cre\sleepdw.cre
del bg1cre\sleepfh.cre
del bg1cre\sleepmh.cre
del bg1cre\squirr.cre
del bg1cre\tasloisu.cre
del bg1cre\tethto2.cre
del bg1cre\tethto3.cre
del bg1cre\voieas.cre
del bg1cre\voinor.cre
del bg1cre\voisou.cre
del bg1cre\voiwes.cre
del bg1cre\voltin.cre
del bg1cre\watch2.cre
del bg1cre\watch3.cre
del bg1cre\watch6.cre
del bg1cre\watch9.cre
del bg1cre\winthr2.cre
del bg1cre\winthr3.cre
del bg1cre\wolfchar.cre
del bg1cre\wolfdi.cre
del bg1cre\wolfdisu.cre
del bg1cre\wolfsu.cre
del bg1cre\worgsu.cre
del bg1cre\xvartsu.cre

::existing and unused creatures
del bg1cre\bird_in.cre
del bg1cre\bird_ine.cre
del bg1cre\bird_inn.cre
del bg1cre\bird_ins.cre
del bg1cre\bird_inw.cre
del bg1cre\charbase.cre
del bg1cre\drunk2.cre
del bg1cre\e31.cre
del bg1cre\e32.cre
del bg1cre\e33.cre
del bg1cre\e34.cre
del bg1cre\e35.cre
del bg1cre\e36.cre
del bg1cre\poghm3.cre
del bg1cre\poghm6.cre
del bg1cre\poghm8.cre
del bg1cre\poghma.cre
del bg1cre\poghma3.cre
del bg1cre\poghma6.cre
del bg1cre\poghma8.cre
del bg1cre\squirl.cre

::bgt-included npcs
del bg1cre\ajanti4.cre
del bg1cre\ajanti6.cre
del bg1cre\ajanti.cre
del bg1cre\alora6.cre
del bg1cre\alora.cre
del bg1cre\branwe5.cre
del bg1cre\branwe.cre
del bg1cre\coran5.cre
del bg1cre\coran.cre
del bg1cre\dynahe2.cre
del bg1cre\dynahe4.cre
del bg1cre\dynahe6.cre
del bg1cre\dynahe.cre
del bg1cre\edwin2.cre
del bg1cre\edwin4.cre
del bg1cre\edwin6.cre
del bg1cre\edwin.cre
del bg1cre\eldoth5.cre
del bg1cre\eldoth.cre
del bg1cre\faldor5.cre
del bg1cre\faldor.cre
del bg1cre\garric2.cre
del bg1cre\garric4.cre
del bg1cre\garric6.cre
del bg1cre\garric.cre
del bg1cre\imoen1.cre
del bg1cre\imoen2.cre
del bg1cre\imoen4.cre
del bg1cre\imoen6.cre
del bg1cre\imoen.cre
del bg1cre\jaheir2.cre
del bg1cre\jaheir4.cre
del bg1cre\jaheir6.cre
del bg1cre\jaheir.cre
del bg1cre\kagain2.cre
del bg1cre\kagain4.cre
del bg1cre\kagain6.cre
del bg1cre\kagain.cre
del bg1cre\khalid2.cre
del bg1cre\khalid4.cre
del bg1cre\khalid6.cre
del bg1cre\khalid.cre
del bg1cre\kivan4.cre
del bg1cre\kivan6.cre
del bg1cre\kivan.cre
del bg1cre\minsc2.cre
del bg1cre\minsc4.cre
del bg1cre\minsc6.cre
del bg1cre\minsc.cre
del bg1cre\montar2.cre
del bg1cre\montar4.cre
del bg1cre\montar6.cre
del bg1cre\montar.cre
del bg1cre\quayle4.cre
del bg1cre\quayle6.cre
del bg1cre\quayle.cre
del bg1cre\safana4.cre
del bg1cre\safana6.cre
del bg1cre\safana.cre
del bg1cre\sharte4.cre
del bg1cre\sharte6.cre
del bg1cre\sharte.cre
del bg1cre\skie6.cre
del bg1cre\skie.cre
del bg1cre\tiax4.cre
del bg1cre\tiax6.cre
del bg1cre\tiax.cre
del bg1cre\viconi4.cre
del bg1cre\viconi6.cre
del bg1cre\viconi.cre
del bg1cre\xan4.cre
del bg1cre\xan6.cre
del bg1cre\xan.cre
del bg1cre\xzar2.cre
del bg1cre\xzar4.cre
del bg1cre\xzar6.cre
del bg1cre\xzar.cre
del bg1cre\yeslic5.cre
del bg1cre\yeslic.cre

